---
title: "Scanpy workflow"
author: "AFL"
date: "5/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python=reticulate::eng_python)
library(reticulate)
use_python("C:/Users/aflorescu/Miniconda3/python.exe") #this work to run but its not knitted 
```



```{python}
import numpy as np
import pandas as pd
import scanpy as sc

```

# Set up workspace
```{python}
sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_header()
sc.settings.set_figure_params(dpi=80, facecolor='white')

```
# Read data and create anndata object

```{python}
results_file = 'C:/data/10x datasets/Example/PBMC3k/pbmc3k.h5ad'


#read data
adata = sc.read_10x_mtx(
    'C:/data/10x datasets/Example/PBMC3k/filtered_gene_bc_matrices/hg19/',  # the directory with the `.mtx` file
    var_names='gene_symbols',                # use gene symbols for the variable names (variables-axis index)
    cache=True)                              # write a cache file for faster subsequent reading
	
adata.var_names_make_unique()  

print(adata)
```
#Preprocessing

Start the workflow in a manner similar to the usual Seurat workflow. First plot highest exprssed genes (seems that thisimplicitly normalized data )

```{python}
sc.pl.highest_expr_genes(adata, n_top=20, )
````
Then filter cells with no genes and genes that are not expressed and do some basic QCs. 
```{python}
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.filter_genes(adata, min_cells=3)

adata.var['mt'] = adata.var_names.str.startswith('MT-')  # annotate the group of mitochondrial genes as 'mt'
sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], percent_top=None, log1p=False, inplace=True)

sc.pl.violin(adata, ['n_genes_by_counts', 'total_counts', 'pct_counts_mt'],
             jitter=0.4, multi_panel=True)
             
sc.pl.scatter(adata, x='total_counts', y='pct_counts_mt')
sc.pl.scatter(adata, x='total_counts', y='n_genes_by_counts')
```

Actually do the filtering by slicing the AnnData object.

```{python}
adata = adata[adata.obs.n_genes_by_counts < 2500, :]
adata = adata[adata.obs.pct_counts_mt < 5, :]
```

Normalize the data to total counts and scale by 10000 (same as Seurat before /outside of SCTransform). There seem to be be some wrappers for SCTransfrom. It is unclear if they would actually be less computationally demanding (to be tested). The also have a seurat recipes that does the normalization and two other different recipes. They also have a method for regressing out variables and Combat.

```{python}
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)

sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)

sc.pl.highly_variable_genes(adata)
```